/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <P1_2_A.h>
#include <P1_2_A_aliases.h>
#include <P3_1_CLK.h>
#include <P3_1_CLK_aliases.h>
#include <P0_6_OE.h>
#include <P0_6_OE_aliases.h>
#include <CR_Addr.h>
#include <P1_1_B.h>
#include <P1_1_B_aliases.h>
#include <P1_5_C.h>
#include <P1_5_C_aliases.h>
#include <P3_0_B2.h>
#include <P3_0_B2_aliases.h>
#include <P1_4_LAT.h>
#include <P1_4_LAT_aliases.h>
#include <P0_7_R1.h>
#include <P0_7_R1_aliases.h>
#include <P3_7_G1.h>
#include <P3_7_G1_aliases.h>
#include <P1_0_G2.h>
#include <P1_0_G2_aliases.h>
#include <P0_0_B1.h>
#include <P0_0_B1_aliases.h>
#include <P3_5_R2.h>
#include <P3_5_R2_aliases.h>
#include <P1_3_done.h>
#include <P1_3_done_aliases.h>
#include <isr_2.h>
#include <LED_Matrix_1.h>
#include <ADC.h>
#include <ADC_P2_0.h>
#include <ADC_P2_0_aliases.h>
#include <ADC_intClock.h>
#include <ADC_IRQ.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

