/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <P2_0_A.h>
#include <P2_0_A_aliases.h>
#include <P2_6_CLK.h>
#include <P2_6_CLK_aliases.h>
#include <P3_6_OE.h>
#include <P3_6_OE_aliases.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <CR_Addr.h>
#include <P2_1_B.h>
#include <P2_1_B_aliases.h>
#include <P2_2_C.h>
#include <P2_2_C_aliases.h>
#include <P2_7_B2.h>
#include <P2_7_B2_aliases.h>
#include <P2_3_LAT.h>
#include <P2_3_LAT_aliases.h>
#include <P0_7_R1.h>
#include <P0_7_R1_aliases.h>
#include <P3_7_G1.h>
#include <P3_7_G1_aliases.h>
#include <P1_0_G2.h>
#include <P1_0_G2_aliases.h>
#include <P0_0_B1.h>
#include <P0_0_B1_aliases.h>
#include <P3_5_R2.h>
#include <P3_5_R2_aliases.h>
#include <P2_4_done.h>
#include <P2_4_done_aliases.h>
#include <isr_2.h>
#include <LED_Matrix_1.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <UART_SCBCLK.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

