//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEES_ADC_DelSig_Mod_v2_30 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KEES_ADC_DelSig_Mod_v2_30.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myclock.
        /// </summary>
        internal static string ClockText {
            get {
                return ResourceManager.GetString("ClockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DsmName.
        /// </summary>
        internal static string DsmNameText {
            get {
                return ResourceManager.GetString("DsmNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM4.
        /// </summary>
        internal static string DSMText {
            get {
                return ResourceManager.GetString("DSMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref value is outside the expected range of 0.9V to 1.3V. Set proper value for Vref..
        /// </summary>
        internal static string ExtRefVrefValueError {
            get {
                return ResourceManager.GetString("ExtRefVrefValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref value is outside the expected range of 0.9V to 1.3V. For Vssa to Vdda input range, the Vref value is derived from Vdda value set in the DWR file. Set proper Vdda value to use Vssa to Vdda input range..
        /// </summary>
        internal static string InputRangeVrefValueError {
            get {
                return ResourceManager.GetString("InputRangeVrefValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vref value is outside the expected range of 0.9V to 1.3V. For Internal Vdda/3 or Internal Vdda/4 and related Bypass reference options, Vref value is derived form Vdda value set in the DWR file. Set proper Vdda value to use Vdda/3 or Vdda/4 or related Bypass reference options..
        /// </summary>
        internal static string ReferenceVrefValueError {
            get {
                return ResourceManager.GetString("ReferenceVrefValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string TrueText {
            get {
                return ResourceManager.GetString("TrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vdda_Value.
        /// </summary>
        internal static string VddaValueText {
            get {
                return ResourceManager.GetString("VddaValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vssa to Vdda and Vssa to 2*Vref input range requires that the input buffer gain be equal to 1. If a gain other than 1 is selected, the ADC will not operate properly..
        /// </summary>
        internal static string VerifyBufferGainErrMsg {
            get {
                return ResourceManager.GetString("VerifyBufferGainErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two configurations of the same name are not allowed. Update the configuration names to be unique..
        /// </summary>
        internal static string VerifyConfigNamesErrMsg {
            get {
                return ResourceManager.GetString("VerifyConfigNamesErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Vssa connection is valid only for PSoC 3. This PSoC 5 device cannot support this feature..
        /// </summary>
        internal static string VerifynVrefSelectionErrorMsg {
            get {
                return ResourceManager.GetString("VerifynVrefSelectionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Vdda/3 and related Bypass Reference options are  valid only for PSoC 3. This PSoC 5 device cannot support this feature. Select another reference option..
        /// </summary>
        internal static string VerifySelectedReferenceErrorMsg {
            get {
                return ResourceManager.GetString("VerifySelectedReferenceErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC Conversion rate selected in one of the configurations is outside the expected range. Set valid conversion rate by invoking components configure window..
        /// </summary>
        internal static string VerifysRateErrMsg {
            get {
                return ResourceManager.GetString("VerifysRateErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Vdda/3 Reference option is valid only for PSoC 3.  This PSoC 5 device cannot support this feature. To use Vssa to Vdda input range for this silicon, set the Vdda value in the Design Wide resource file to above 3.75V..
        /// </summary>
        internal static string VerifyVssaToVddaSelectedReference {
            get {
                return ResourceManager.GetString("VerifyVssaToVddaSelectedReference", resourceCulture);
            }
        }
    }
}
